### PR TITLE
feat: Allow using file-likes as wallpapers

### PR DESCRIPTION
**Pull request by ghost**
This might be useful in case you don't want to manually store a wallpaper, hence not passing in a file path but a file-like as follows:

```scheme
(origin
  (method url-fetch)
  (uri "https://w.wallhaven.cc/full/28/wallhaven-<id>.jpg")
  (sha256 
    (base32 "<hash>")))
```

### CODE REVIEW

**Comment by Frewacom** [comment]
Hi, sorry for the late response. 

This sounds like a really good idea. I assume the pywal generator won't be able to support this, since it needs to be run manually before writing anything to the store, but that is fine. 

Have you checked if this works as expected? 

Also, since we are using channel authentication, we need to add your GPG key to the `keyring` branch in order for you to merge code into main. Do you want to set that up, or should I re-commit and push the changes myself?

**Comment by ghost** [comment]
Hi! Not sure about the implications on the`pywal` generator, I haven't used it yet. I've checked these changes work in my config (see [this commit](https://github.com/migalmoreno/guix-config/commit/bd1f6dc87ab37b0beecf08cfea5625bf5dfd20b5) and the two previous ones). Wrt channel authentication, I'll send another PR with my public key

**Comment by Frewacom** [comment]
Hi!

Could you rebase your branch against main? I think the channel authentication will fail after merging due to me adding your GPG key to `.guix-authorizations` after the commit in this PR.

**Comment by ghost** [comment]
@Frewacom Sorry for the late reply! Just rebased it on top of main.

**Pull request closed without merging**
